// SPDX-License-Identifier: GPL-3.0-only — © 2026 AIB Inc. https://www.aib.vote
import './style.css';
import {createStorm,type StormSettings} from './scene';
const $=<E extends HTMLElement=HTMLElement>(query:string)=>document.querySelector<E>(query)!;
const preview=new URLSearchParams(location.search).has('preview'),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const settings:StormSettings={density:.5,branching:.68,wind:.32,interval:2.6,dome:true,fast:false,paused:preview||reduced};
$('#app').innerHTML=`<header><a class="brand" href="../../#collection" aria-label="Back to Wonderworks"><span class="brand-icon">✳</span> WONDERWORKS</a><span class="chapter">FIELD NOTES <span class="line"></span> No. 008</span><button id="sound" class="icon-button" aria-pressed="false"><span class="sound-icon">◌</span> Sound off</button></header>
<section class="identity"><p class="eyebrow"><i></i> AN ATMOSPHERIC EXPERIMENT</p><h1>Fulgur<span>.</span></h1><p class="subtitle">A small storm,<br><em>held in wonder.</em></p><div class="identity-rule"></div><p class="description">The quiet before.<br>The light within.</p></section>
<aside class="instruments" aria-label="Storm controls"><div class="instrument-heading"><span>THE ATMOSPHERE</span><span>01—03</span></div><label for="density"><span>Cloud body</span><output id="density-value">50%</output></label><input id="density" type="range" min=".35" max="1" step=".01" value=".5"><label for="branching"><span>Branching</span><output id="branching-value">68%</output></label><input id="branching" type="range" min="0" max="1" step=".01" value=".68"><label for="wind"><span>Drift</span><output id="wind-value">32%</output></label><input id="wind" type="range" min="0" max="1" step=".01" value=".32"><div class="surface"><span>GROUND</span><div class="chips" role="group" aria-label="Ground surface"><button data-ground="dome" aria-pressed="true">Dome</button><button data-ground="plane" aria-pressed="false">Plane</button></div></div><div class="surface playback"><span>TIME</span><div class="chips" role="group" aria-label="Playback speed"><button data-speed="natural" aria-pressed="true">Natural</button><button data-speed="fast" aria-pressed="false">Fast</button></div></div><div class="readout"><span class="live-dot"></span><span id="state-label">Gathering charge</span><span id="count">000</span></div></aside>
<div class="stage-label"><span>01 / CUMULONIMBUS</span><span>BRANCHING DISCHARGE STUDY</span></div>
<footer><div class="instructions"><span class="gesture">↔</span><div>Drag to explore<span>Scroll to move closer · Click to strike</span></div></div><div class="actions"><button id="strike" class="primary"><span>↯</span> Summon lightning <kbd>↵</kbd></button><button id="pause" class="secondary" aria-label="Pause simulation">Ⅱ</button><button id="save" class="secondary" aria-label="Save a photograph">↗</button></div><button id="reset" class="reset">Reset view <span>↺</span></button></footer>
<div class="fineprint"><a href="https://www.aib.vote" target="_blank" rel="noopener">© 2026 AIB Inc.</a><span>FLASHING LIGHT · PAUSE ANYTIME</span></div><p id="notice" role="status" aria-live="polite"></p>`;
if(preview)document.body.classList.add('preview');
if(import.meta.env.DEV)$<HTMLAnchorElement>('.brand').href='https://wonderworks.vercel.app/#collection';
let audio:AudioContext|undefined,muted=true,noise:AudioBuffer|undefined,noticeTimer=0;
function notify(message:string){$('#notice').textContent=message;clearTimeout(noticeTimer);noticeTimer=window.setTimeout(()=>$('#notice').textContent='',4500);}
function thunder(energy:number){if(muted||!audio||audio.state!=='running'||!noise)return;const now=audio.currentTime+.22,source=audio.createBufferSource(),gain=audio.createGain(),filter=audio.createBiquadFilter();source.buffer=noise;filter.type='lowpass';filter.frequency.value=170;source.connect(filter).connect(gain).connect(audio.destination);gain.gain.setValueAtTime(0,now);gain.gain.linearRampToValueAtTime(.26*energy,now+.12);gain.gain.exponentialRampToValueAtTime(.001,now+2.6);source.start(now);source.stop(now+2.8);source.onended=()=>{source.disconnect();filter.disconnect();gain.disconnect();};}
$('#sound').onclick=async()=>{try{if(!audio){audio=new AudioContext();noise=audio.createBuffer(1,audio.sampleRate*3,audio.sampleRate);const data=noise.getChannelData(0);let previous=0;for(let i=0;i<data.length;i++){previous=(previous+(Math.random()*2-1)*.12)/1.03;data[i]=previous*3;}}muted=!muted;if(muted)await audio.suspend();else await audio.resume();$('#sound').setAttribute('aria-pressed',String(!muted));$('#sound').innerHTML=`<span class="sound-icon">${muted?'◌':'◉'}</span> Sound ${muted?'off':'on'}`;}catch(e){notify(e instanceof Error?e.message:'Sound could not start.');}};
try{
 const scene=createStorm($<HTMLCanvasElement>('#world'),settings,energy=>{thunder(energy);},message=>{$('#error').hidden=false;$('#error').textContent=message;});
 $('#loading').hidden=true;document.body.classList.add('ready');
 for(const key of ['density','branching','wind'] as const){const slider=$<HTMLInputElement>('#'+key);slider.oninput=()=>{settings[key]=Number(slider.value);$('#'+key+'-value').textContent=Math.round(settings[key]*100)+'%';if(key==='branching')scene.refreshBranching();else scene.update();};}
 for(const button of document.querySelectorAll<HTMLButtonElement>('[data-ground]'))button.onclick=()=>{settings.dome=button.dataset.ground==='dome';document.querySelectorAll<HTMLButtonElement>('[data-ground]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));scene.strike();};
 for(const button of document.querySelectorAll<HTMLButtonElement>('[data-speed]'))button.onclick=()=>{settings.fast=button.dataset.speed==='fast';document.querySelectorAll<HTMLButtonElement>('[data-speed]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));scene.update();};
 const pause=()=>{settings.paused=!settings.paused;scene.pause();$('#pause').textContent=settings.paused?'▷':'Ⅱ';$('#pause').setAttribute('aria-label',settings.paused?'Resume simulation':'Pause simulation');if(audio&&!muted){void(settings.paused?audio.suspend():audio.resume());}};
 $('#pause').onclick=pause;$('#pause').textContent=settings.paused?'▷':'Ⅱ';$('#pause').setAttribute('aria-label',settings.paused?'Resume simulation':'Pause simulation');
 $('#strike').onclick=()=>scene.strike();$('#reset').onclick=()=>scene.reset();
 $('#save').onclick=async()=>{try{const blob=await scene.capture(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='fulgur-a-small-storm.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notify('A little weather to keep.');}catch(e){notify(e instanceof Error?e.message:'Unable to save the image.');}};
 const statusTimer=window.setInterval(()=>{if(document.hidden)return;const status=scene.status();const count=String(status.strikes).padStart(3,'0'),label=status.paused?'A moment, held':status.leader?'Leader forming':status.returning?'Return stroke':status.afterglow?'Afterglow':'Gathering charge';if($('#count').textContent!==count)$('#count').textContent=count;if($('#state-label').textContent!==label)$('#state-label').textContent=label;},300);
 addEventListener('keydown',event=>{if((event.target as HTMLElement).matches('button,input,a'))return;if(event.code==='Space'){event.preventDefault();pause();}if(event.code==='Enter')scene.strike();});
 addEventListener('pagehide',e=>{if(e.persisted)scene.setActive(false);else{clearInterval(statusTimer);clearTimeout(noticeTimer);scene.dispose();void audio?.close();}});addEventListener('pageshow',e=>{if(e.persisted)scene.setActive(true);});
 document.addEventListener('visibilitychange',()=>{if(audio&&!muted)void(document.hidden||settings.paused?audio.suspend():audio.resume());});
 if(preview){parent.postMessage({type:'wonderworks:ready'},location.origin);addEventListener('message',event=>{if(event.origin!==location.origin||event.source!==parent)return;if(event.data?.type==='wonderworks:play'){settings.paused=false;scene.pause();}if(event.data?.type==='wonderworks:pause'){settings.paused=true;scene.pause();}});}
 if(import.meta.env.DEV)Object.defineProperty(window,'stormDiagnostics',{value:scene.diagnostics});
}catch(e){console.error(e);$('#loading').hidden=true;$('#error').hidden=false;$('#error').textContent='This little storm needs WebGL 2. Please try a browser with graphics acceleration enabled.';}
