// SPDX-License-Identifier: GPL-3.0-only — © 2026 AIB Inc. https://www.aib.vote
import {createScene,type View} from './scene';
import type {Settings} from './shared';
const $=<E extends HTMLElement=HTMLElement>(s:string)=>document.querySelector<E>(s)!;
const preview=new URLSearchParams(location.search).has('preview');
const settings:Settings={hour:14.5,clarity:.91,breeze:.35,activity:1,rain:false,paused:matchMedia('(prefers-reduced-motion:reduce)').matches,roam:false};
$('#ui').innerHTML=`<header><a class="back" href="../../#collection" aria-label="Back to Wonderworks">↖ <span>WONDERWORKS</span></a><span class="edition">A LIVING WATER GARDEN <i></i> STUDY 007</span><button id="settings-toggle" aria-expanded="false" aria-controls="settings">Tune the garden <span>☷</span></button></header>
<section class="identity"><p class="eyebrow">PAUSE. LOOK A LITTLE CLOSER.</p><h1>Still<span>water</span><em>.</em></h1><p class="intro">A small world, just beneath the surface.</p></section>
<aside id="settings" hidden aria-label="Garden settings"><div class="panel-heading"><h2>Make yourself at home.</h2><button id="settings-close" aria-label="Close settings">×</button></div><p>A different light. The same little world.</p><div class="moods" role="group" aria-label="Atmosphere"><button data-mood="sun" aria-pressed="true">Sunlit</button><button data-mood="dusk" aria-pressed="false">Dusk</button><button data-mood="rain" aria-pressed="false">Soft rain</button></div><label>Time of day <output id="hour-value">14:30</output><input id="hour" type="range" min="6" max="21" step=".1" value="14.5"></label><label>Water clarity <output id="clarity-value">91%</output><input id="clarity" type="range" min=".15" max="1" step=".01" value=".91"></label><label>Surface breeze <output id="breeze-value">35%</output><input id="breeze" type="range" min="0" max="1" step=".01" value=".35"></label><label>Swimming energy <output id="activity-value">100%</output><input id="activity" type="range" min=".3" max="2" step=".05" value="1"></label><div class="panel-actions"><button id="pause">Pause</button><button id="roam" aria-pressed="false">Slow orbit</button><button id="save">Save a moment ↗</button></div><a class="credit" href="./models/ATTRIBUTION.md" target="_blank" rel="noopener">Animal models · Credits & CC BY 4.0 ↗</a><a class="credit" href="https://www.aib.vote" target="_blank" rel="noopener">© 2026 AIB Inc.</a></aside>
<footer><div class="observations"><span class="live-dot"></span><span id="observation">8 goldfish · One quiet afternoon</span><small>DRAG TO LOOK · SCROLL TO EXPLORE · TAP FOR RIPPLES</small></div><nav aria-label="Camera viewpoints"><button data-view="garden" aria-pressed="true"><span>01</span> Garden</button><button data-view="waterline" aria-pressed="false"><span>02</span> Waterline</button><button data-view="dive" aria-pressed="false"><span>03</span> Dive in</button><button data-view="lilies" aria-pressed="false"><span>04</span> Lily pads</button></nav><button id="feed"><span>⋅⁘⋅</span> Feed the fish</button></footer><p id="notice" role="status" aria-live="polite"></p>`;
if(preview)document.body.classList.add('preview');if(import.meta.env.DEV)$<HTMLAnchorElement>('.back').href='http://127.0.0.1:4175/#collection';
const error=(msg:string)=>{$('#error').hidden=false;$('#error').textContent=msg;$('#loading').hidden=true;if(preview)parent.postMessage({type:'wonderworks:error'},location.origin);};
try{
 const scene=await createScene($<HTMLCanvasElement>('#world'),settings,error,()=>$('#roam').setAttribute('aria-pressed','false'));
 let noteTimer=0;const notice=(msg:string)=>{$('#notice').textContent=msg;clearTimeout(noteTimer);noteTimer=window.setTimeout(()=>$('#notice').textContent='',3500);};
 const setView=(view:View)=>{scene.setView(view);document.querySelectorAll<HTMLButtonElement>('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===view)));$('#observation').textContent=({garden:'8 goldfish · One quiet afternoon',waterline:'Between the garden and its reflection',dive:'Follow the light beneath the surface',lilies:'Move near or tap the frog — watch it leap'})[view];};
 document.querySelectorAll<HTMLButtonElement>('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view as View));
 const panel=(open:boolean)=>{$('#settings').hidden=!open;$('#settings-toggle').setAttribute('aria-expanded',String(open));if(open)$('#settings-close').focus();else $('#settings-toggle').focus();};$('#settings-toggle').onclick=()=>panel($('#settings').hasAttribute('hidden'));$('#settings-close').onclick=()=>panel(false);
 function sync(){for(const key of ['hour','clarity','breeze','activity'] as const){$<HTMLInputElement>('#'+key).value=String(settings[key]);$('#'+key+'-value').textContent=key==='hour'?`${Math.floor(settings.hour).toString().padStart(2,'0')}:${Math.round(settings.hour%1*60).toString().padStart(2,'0')}`:Math.round(settings[key]*100)+'%';}scene.update();}
 for(const key of ['hour','clarity','breeze','activity'] as const)$<HTMLInputElement>('#'+key).oninput=e=>{settings[key]=Number((e.target as HTMLInputElement).value);sync();};
 document.querySelectorAll<HTMLButtonElement>('[data-mood]').forEach(b=>b.onclick=()=>{settings.rain=b.dataset.mood==='rain';settings.hour=b.dataset.mood==='dusk'?18.5:14.5;settings.breeze=settings.rain?.65:.35;document.querySelectorAll('[data-mood]').forEach(el=>el.setAttribute('aria-pressed',String(el===b)));sync();});
 const pause=()=>{settings.paused=!settings.paused;$('#pause').textContent=settings.paused?'Resume':'Pause';scene.pause();};$('#pause').onclick=pause;$('#pause').textContent=settings.paused?'Resume':'Pause';$('#roam').onclick=()=>{settings.roam=!settings.roam;$('#roam').setAttribute('aria-pressed',String(settings.roam));scene.update();};$('#feed').onclick=()=>{if(settings.paused){notice('Resume the garden to feed the fish.');return;}scene.feed();notice('A little patience. They are coming closer.');};
 $('#save').onclick=async()=>{try{const blob=await scene.snapshot(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='stillwater.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notice('A moment to keep.');}catch(e){notice(e instanceof Error?e.message:'Unable to save the image.');}};
 addEventListener('keydown',e=>{if(e.key==='Escape'){panel(false);return;}if((e.target as HTMLElement).matches('input,button,a'))return;if(e.code==='Space'){e.preventDefault();pause();}const views:View[]=['garden','waterline','dive','lilies'];if(['1','2','3','4'].includes(e.key))setView(views[Number(e.key)-1]!);if(e.key.toLowerCase()==='f')$('#feed').click();});
 addEventListener('pagehide',e=>{if(e.persisted)scene.setActive(false);else scene.dispose();});addEventListener('pageshow',e=>{if(e.persisted)scene.setActive(true);});
 if(preview){settings.paused=true;scene.pause();addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==parent)return;if(e.data?.type==='wonderworks:play'){settings.paused=false;scene.pause();}if(e.data?.type==='wonderworks:pause'){settings.paused=true;scene.pause();}});}
 Object.defineProperty(window,'pondDiagnostics',{value:scene.diagnostics});requestAnimationFrame(()=>{$('#loading').hidden=true;document.body.classList.add('ready');if(preview)parent.postMessage({type:'wonderworks:ready'},location.origin);});
}catch(e){console.error(e);error(e instanceof Error?e.message:'The garden could not start. Please reload.');}
