import {terrainHeight} from './terrain';
// SPDX-License-Identifier: GPL-3.0-only — © 2026 AIB Inc.
import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {createGarden} from './garden';
import {createLife} from './life';
import {createDrifting} from './drifting';
import {createWater} from './water';
import {createBackdrop} from './backdrop';
import {rng,uTime,noiseGLSL,type Settings} from './shared';
export type View='garden'|'waterline'|'dive'|'lilies';
export async function createScene(canvas:HTMLCanvasElement,s:Settings,onError:(message:string)=>void,onManual:()=>void){
 const renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setClearColor('#a9c4b5');renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.0;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFShadowMap;renderer.shadowMap.autoUpdate=false;
 const world=new T.Scene();world.fog=new T.FogExp2('#b8cbbb',.009);const pmrem=new T.PMREMGenerator(renderer),room=new RoomEnvironment(),env=pmrem.fromScene(room,.05);world.environment=env.texture;world.environmentIntensity=.45;room.dispose();pmrem.dispose();
 const camera=new T.PerspectiveCamera(43,1,.045,210);camera.position.set(8.8,5.2,13.6);const orbit=new OrbitControls(camera,canvas);orbit.target.set(0,.5,-1);orbit.enableDamping=true;orbit.dampingFactor=.08;orbit.enablePan=true;orbit.screenSpacePanning=false;orbit.panSpeed=.75;orbit.mouseButtons.RIGHT=T.MOUSE.PAN;orbit.cursor.set(0,.3,-1);orbit.maxTargetRadius=16;orbit.listenToKeyEvents(canvas);orbit.minDistance=.65;orbit.maxDistance=38;orbit.maxPolarAngle=Math.PI/2;orbit.minPolarAngle=.13;orbit.rotateSpeed=.6;orbit.update();
 const hemi=new T.HemisphereLight('#e2f0ec','#4b5940',2.2);world.add(hemi);const sun=new T.DirectionalLight('#fff0cf',3.8);sun.position.set(-12,20,8);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-20,right:20,top:20,bottom:-20,near:.5,far:65});sun.shadow.normalBias=.035;sun.shadow.bias=-.00018;sun.shadow.radius=3;world.add(sun);
 const skyMat=new T.ShaderMaterial({side:T.BackSide,depthWrite:false,uniforms:{top:{value:new T.Color('#92b8c5')},bottom:{value:new T.Color('#e7e4c9')},uTime},vertexShader:'varying vec3 vP;void main(){vP=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:`varying vec3 vP;uniform vec3 top;uniform vec3 bottom;uniform float uTime;${noiseGLSL}void main(){vec3 d=normalize(vP);float h=max(d.y,0.);vec3 col=mix(bottom,top,pow(h,.5));vec2 p=d.xz/max(.18,d.y)*2.;float clouds=smoothstep(.52,.8,noise2(p*.9+uTime*.005)*.65+noise2(p*2.1)*.35)*smoothstep(0.,.3,h);col=mix(col,vec3(.92,.93,.87),clouds*.52);gl_FragColor=vec4(col,1.);\n#include <tonemapping_fragment>\n#include <colorspace_fragment>}`});const sky=new T.Mesh(new T.SphereGeometry(110,24,16),skyMat);world.add(sky);
 const backdrop=await createBackdrop(world);
 const garden=await createGarden(world);const water=createWater(world,renderer,camera,s);const life=await createLife(world,water.ripple);const rand=rng(72);
 const drifting=createDrifting(world);
 const rainG=new T.BufferGeometry(),rainP=new Float32Array(800*6);for(let i=0;i<800;i++){const x=(rand()-.5)*24,y=rand()*15,z=(rand()-.5)*19;rainP.set([x,y,z,x+.022,y-.23,z],i*6);}rainG.setAttribute('position',new T.BufferAttribute(rainP,3));const rain=new T.LineSegments(rainG,new T.ShaderMaterial({uniforms:{uTime},transparent:true,opacity:.4,depthWrite:false,vertexShader:`uniform float uTime;void main(){vec3 p=position;p.y=mod(p.y-uTime*7.+1500.,15.);p.x+=sin(uTime*.1)*.4;gl_Position=projectionMatrix*modelViewMatrix*vec4(p,1.);}`,fragmentShader:'void main(){gl_FragColor=vec4(.78,.89,.9,.23);}'}));rain.visible=false;world.add(rain);
 const startPos=new T.Vector3(),startTarget=new T.Vector3(),endPos=new T.Vector3(),endTarget=new T.Vector3();let travel=-1,view:View='garden',frames=0,raf=0,last=0,disposed=false,active=true,rainTick=0;const fogColor=new T.Color();
 function setView(next:View){view=next;startPos.copy(camera.position);startTarget.copy(orbit.target);const mobile=canvas.clientWidth/canvas.clientHeight<.8;
 const data:Record<View,[number[],number[]]>={garden:[[8.8,5.2,13.6],[0,.3,-1]],waterline:[[.8,1.05,7.3],[0,.2,-4.5]],dive:[[0,-.58,5.7],[-1,-.7,-1.8]],lilies:[[-3.1,1.6,5.5],[-5.2,.08,2.7]]};endPos.fromArray(data[next][0]);endTarget.fromArray(data[next][1]);if(mobile&&next==='garden')endPos.multiplyScalar(1.12);travel=0;invalidate();}
 function frameDraw(dt:number){
 if(!s.paused){uTime.value+=dt;life.update(dt,s.activity,s.breeze);drifting.update(s.breeze);if(s.rain){rainTick+=dt;if(rainTick>.13){rainTick=0;water.ripple((rand()-.5)*15,(rand()-.5)*10,.24);}}}
 if(travel>=0){travel=Math.min(travel+dt/2.6,1);const ease=travel*travel*(3-2*travel);camera.position.lerpVectors(startPos,endPos,ease);orbit.target.lerpVectors(startTarget,endTarget,ease);if(travel===1)travel=-1;}
 orbit.autoRotate=s.roam&&!s.paused&&travel<0&&view==='garden';orbit.autoRotateSpeed=.22;orbit.update();
 // Orbit limits alone depend on the target height. Enforce terrain clearance
 // after zoom, damping and preset travel as well, while retaining the dive view.
 const floorY=terrainHeight(camera.position.x,camera.position.z);
 if(camera.position.y<floorY+.22){camera.position.y=floorY+.22;camera.lookAt(orbit.target);}
 const angle=(s.hour-6)/12*Math.PI,day=T.MathUtils.smoothstep(Math.sin(angle),-.12,.22);sun.position.set(Math.cos(angle)*19,Math.max(1.5,Math.sin(angle)*25),-7);sun.intensity=day*(s.rain?1.25:2.8);sun.color.setRGB(1,.73+.23*day,.49+.36*day);hemi.intensity=.45+day*1.1;world.environmentIntensity=.25+day*.4;skyMat.uniforms.top!.value.set(day>.5?'#86b9c6':'#26394f');skyMat.uniforms.bottom!.value.set(day>.5?'#dedfc7':'#c2a087');water.uniforms.uSun.value.copy(sun.position).normalize();water.uniforms.uSunColor.value.copy(sun.color).multiplyScalar(day);rain.visible=s.rain;backdrop.update(day,s.rain);
 const under=camera.position.y<0;fogColor.set(under?'#1c5148':day>.5?'#bbd0c1':'#4b6169');(world.fog as T.FogExp2).color.copy(fogColor);(world.fog as T.FogExp2).density=under?(.025+(1-s.clarity)*.035):s.rain?.023:.009;water.render();frames++;
 }
 function frame(now:number){raf=0;if(disposed||!active||document.hidden)return;const dt=last?Math.min((now-last)/1000,.05):0;last=now;frameDraw(s.paused&&travel<0?0:dt);if(!s.paused||travel>=0)raf=requestAnimationFrame(frame);}
 function invalidate(){if(!raf&&active&&!disposed&&!document.hidden)raf=requestAnimationFrame(frame);}
 function stop(){cancelAnimationFrame(raf);raf=0;last=0;}
 orbit.addEventListener('start',()=>{travel=-1;s.roam=false;onManual();});orbit.addEventListener('change',()=>{if(s.paused)invalidate();});
 const ray=new T.Raycaster(),plane=new T.Plane(new T.Vector3(0,1,0),0),hit=new T.Vector3();let down:{x:number;y:number;id:number}|null=null;
 const onDown=(e:PointerEvent)=>{if(e.isPrimary&&e.button===0&&!e.ctrlKey&&!e.metaKey&&!e.shiftKey)down={x:e.clientX,y:e.clientY,id:e.pointerId};else down=null;};const onUp=(e:PointerEvent)=>{if(!down||down.id!==e.pointerId||Math.hypot(e.clientX-down.x,e.clientY-down.y)>7){down=null;return;}down=null;const rect=canvas.getBoundingClientRect();ray.setFromCamera(new T.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),camera);if(!s.paused&&life.frog.react(ray.ray,uTime.value,true)){invalidate();return;}if(ray.ray.intersectPlane(plane,hit)&&hit.x*hit.x/100+hit.z*hit.z/56<1){water.ripple(hit.x,hit.z,1);invalidate();}};const onCancel=()=>{down=null;};canvas.addEventListener('pointerdown',onDown);canvas.addEventListener('pointerup',onUp);canvas.addEventListener('pointercancel',onCancel);
 const onMove=(e:PointerEvent)=>{if(s.paused||e.buttons||e.pointerType==='touch')return;const rect=canvas.getBoundingClientRect();ray.setFromCamera(new T.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),camera);if(life.frog.react(ray.ray,uTime.value,false))invalidate();};const onLeave=()=>life.frog.clearHover();canvas.addEventListener('pointermove',onMove);canvas.addEventListener('pointerleave',onLeave);
 let prevW=0,prevH=0;const resize=new ResizeObserver(()=>{const w=canvas.clientWidth,h=canvas.clientHeight;if(!w||!h)return;const ratio=Math.min(devicePixelRatio,1.6,Math.sqrt(2000000/(w*h)));const pw=Math.round(w*ratio),ph=Math.round(h*ratio);if(pw===prevW&&ph===prevH)return;prevW=pw;prevH=ph;renderer.setPixelRatio(ratio);renderer.setSize(w,h,false);camera.aspect=w/h;camera.fov=w/h<.8?60:43;camera.updateProjectionMatrix();water.resize(canvas.width,canvas.height);invalidate();});resize.observe(canvas);
 const hidden=()=>{stop();if(!document.hidden)invalidate();};document.addEventListener('visibilitychange',hidden);const lost=(e:Event)=>{e.preventDefault();active=false;stop();onError('The graphics connection was interrupted. Reload to return to the garden.');};canvas.addEventListener('webglcontextlost',lost);life.update(0,s.activity,s.breeze);
 return {setView,update:invalidate,pause(){stop();invalidate();},feed(){const p=view==='lilies'?life.lilyTarget:orbit.target;life.feed(T.MathUtils.clamp(p.x,-7,7),T.MathUtils.clamp(p.z,-4,4));invalidate();},setActive(value:boolean){active=value;stop();if(value)invalidate();},snapshot(){frameDraw(0);return new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('Unable to capture the garden.')),'image/png'));},diagnostics(){return {frames,time:uTime.value,view,fish:life.positions.length,life:life.diagnostics(),drifting:drifting.counts,leaves:garden.leaves,architecture:garden.architecture.map(a=>({name:a.name,min:a.bounds.min.toArray(),max:a.bounds.max.toArray()})),backdrop:{kind:'painted-panorama',triangles:backdrop.triangles},meadow:garden.meadow,feeding:life.feedActive,paused:s.paused,active,draws:renderer.info.render.calls,triangles:renderer.info.render.triangles,canvas:[canvas.width,canvas.height],camera:camera.position.toArray(),target:orbit.target.toArray(),pendingFrame:!!raf};},dispose(){disposed=true;stop();resize.disconnect();orbit.dispose();document.removeEventListener('visibilitychange',hidden);canvas.removeEventListener('webglcontextlost',lost);canvas.removeEventListener('pointerdown',onDown);canvas.removeEventListener('pointerup',onUp);canvas.removeEventListener('pointercancel',onCancel);canvas.removeEventListener('pointermove',onMove);canvas.removeEventListener('pointerleave',onLeave);const geometries=new Set<T.BufferGeometry>(),materials=new Set<T.Material>(),textures=new Set<T.Texture>();world.traverse(o=>{if(o instanceof T.Mesh||o instanceof T.Points||o instanceof T.Line){geometries.add(o.geometry);for(const m of Array.isArray(o.material)?o.material:[o.material]){materials.add(m);for(const v of Object.values(m))if(v instanceof T.Texture)textures.add(v);}}});geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());textures.forEach(t=>t.dispose());drifting.dispose();water.dispose();env.dispose();renderer.dispose();}};
}
