// SPDX-License-Identifier: GPL-3.0-only — © 2026 AIB Inc.
import * as T from 'three';
import {causticGLSL,waterUniforms} from './water-field';
export const tau=Math.PI*2;
export const rng=(seed:number)=>()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296;};
export const uTime={value:0};
export interface Settings{hour:number;clarity:number;breeze:number;activity:number;glow:number;rain:boolean;paused:boolean;roam:boolean;}
export const noiseGLSL=`float hash21(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);} float noise2(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hash21(i),hash21(i+vec2(1,0)),f.x),mix(hash21(i+vec2(0,1)),hash21(i+1.),f.x),f.y);}`;
export function underwaterLight(material:T.MeshStandardMaterial){material.onBeforeCompile=shader=>{Object.assign(shader.uniforms,waterUniforms);shader.uniforms.uPondTime=uTime;shader.vertexShader=shader.vertexShader.replace('#include <common>','#include <common>\nvarying vec3 vPondWorld;').replace('#include <worldpos_vertex>','#include <worldpos_vertex>\nvPondWorld=(modelMatrix*vec4(transformed,1.)).xyz;');shader.fragmentShader=shader.fragmentShader.replace('#include <common>',`#include <common>\nuniform float uPondTime;varying vec3 vPondWorld;${causticGLSL}`).replace('#include <emissivemap_fragment>','#include <emissivemap_fragment>\nfloat wet=1.-smoothstep(-.06,.06,vPondWorld.y);totalEmissiveRadiance+=diffuseColor.rgb*vec3(.24,.28,.20)*causticLight(vPondWorld)*wet;diffuseColor.rgb=mix(diffuseColor.rgb,diffuseColor.rgb*vec3(.66,.88,.75),wet*.38);');};return material;}
export function texture(kind:'rock'|'bark'|'sand'|'wood'){
 const c=document.createElement('canvas');c.width=c.height=512;const ctx=c.getContext('2d')!;const image=ctx.createImageData(512,512),r=rng(701);for(let y=0;y<512;y++)for(let x=0;x<512;x++){let n=r();const grain=Math.sin(x*.24+Math.sin(y*.014)*4+Math.sin(x*.052+y*.019)*2)*.5+.5;const v=kind==='bark'?36+grain*42+n*24:kind==='wood'?48+grain*44+n*12:kind==='sand'?110+n*55+Math.sin(x*.05+y*.03)*9:65+n*47+Math.sin(x*.037)*Math.cos(y*.047)*16;const i=(y*512+x)*4;image.data[i]=v*(kind==='wood'?1.25:1);image.data[i+1]=v*(kind==='bark'?.84:kind==='wood'?.78:1.04);image.data[i+2]=v*(kind==='wood'?.5:kind==='bark'?.63:.91);image.data[i+3]=255;}ctx.putImageData(image,0,0);if(kind==='sand'){ctx.fillStyle='#5e675c';ctx.fillRect(0,0,512,512);for(let j=0;j<4200;j++){const x=r()*512,y=r()*512,rad=2+r()*5,v=65+r()*65;ctx.beginPath();ctx.ellipse(x,y,rad,rad*(.55+r()*.3),r()*3.14,0,Math.PI*2);const gradient=ctx.createRadialGradient(x-rad*.3,y-rad*.35,0,x,y,rad);gradient.addColorStop(0,`rgb(${v+24},${v+28},${v+14})`);gradient.addColorStop(1,`rgb(${v*.56},${v*.61},${v*.53})`);ctx.fillStyle=gradient;ctx.fill();}}const t=new T.CanvasTexture(c);t.wrapS=t.wrapT=T.RepeatWrapping;t.colorSpace=T.SRGBColorSpace;t.anisotropy=4;return t;
}
