// SPDX-License-Identifier: GPL-3.0-only — © 2026 AIB Inc.
import type { ReadingPage } from './random';

// 100 text-rich public pages checked with the original-view renderer on 2026-10-03.
// Selection criteria and source URLs: docs/crawler/RANDOM_PAGES.md.
export const readingPages: readonly ReadingPage[] = [
  {"title": "Adactio: Journal—Gaeilge sa Ghréig", "url": "https://adactio.com/journal/22643", "language": "en"},
  {"title": "Adactio: Journal—Summer’s end", "url": "https://adactio.com/journal/22166", "language": "en"},
  {"title": "Adactio: Journal—The summer of ’26", "url": "https://adactio.com/journal/22774", "language": "en"},
  {"title": "Adactio: Journal—Think local", "url": "https://adactio.com/journal/22778", "language": "en"},
  {"title": "Adactio: Journal—Threat models", "url": "https://adactio.com/journal/22529", "language": "en"},
  {"title": "Adactio: Journal—Twenty five years of writing on adactio.com", "url": "https://adactio.com/journal/22781", "language": "en"},
  {"title": "Adactio: Journal—Welcome to my world", "url": "https://adactio.com/journal/1", "language": "en"},
  {"title": "『1000xRESIST』 ⇠ 사색송어", "url": "https://ahnheejong.name/articles/1000xresist", "language": "ko"},
  {"title": "『가능한 사랑』 ⇠ 사색송어", "url": "https://ahnheejong.name/articles/possible-love", "language": "ko"},
  {"title": "계단과 벌판 ⇠ 사색송어", "url": "https://ahnheejong.name/articles/stairway-and-field", "language": "ko"},
  {"title": "떠날 준비, 돌아가며 ⇠ 사색송어", "url": "https://ahnheejong.name/articles/always-leaving-always-returning", "language": "ko"},
  {"title": "빌라쥬 드 아난티 ⇠ 사색송어", "url": "https://ahnheejong.name/articles/village-de-ananti", "language": "ko"},
  {"title": "씁쓸한 하루, 달콤한 집 ⇠ 사색송어", "url": "https://ahnheejong.name/articles/bitter-day-sweet-home", "language": "ko"},
  {"title": "500 Lines or LessIntroduction", "url": "https://aosabook.org/en/500L/introduction.html", "language": "en"},
  {"title": "Beej's Guide to Network Programming", "url": "https://beej.us/guide/bgnet/html/split/intro.html", "language": "en"},
  {"title": "Attention is your scarcest resource | benkuhn.net", "url": "https://www.benkuhn.net/attention/", "language": "en"},
  {"title": "In defense of blub studies | benkuhn.net", "url": "https://www.benkuhn.net/blub/", "language": "en"},
  {"title": "No one can teach you to have conviction | benkuhn.net", "url": "https://www.benkuhn.net/conviction/", "language": "en"},
  {"title": "To listen well, get curious | benkuhn.net", "url": "https://www.benkuhn.net/listen/", "language": "en"},
  {"title": "River: a Fast, Robust Job Queue for Go + Postgres — brandur.org", "url": "https://brandur.org/river", "language": "en"},
  {"title": "The Minimum Viable Unit of Saleable Software — brandur.org", "url": "https://brandur.org/minimum-viable-unit", "language": "en"},
  {"title": "Building LLMs is probably not going be a brilliant business", "url": "https://calpaterson.com/porter.html", "language": "en"},
  {"title": "Dependency cooldowns turn you into a free-rider", "url": "https://calpaterson.com/deps.html", "language": "en"},
  {"title": "Is Tesla really more valuable than Toyota?", "url": "https://calpaterson.com/singleton.html", "language": "en"},
  {"title": "The Internet Classics Archive | Apology by Plato", "url": "https://classics.mit.edu/Plato/apology.html", "language": "en"},
  {"title": "Clojure - Rationale", "url": "https://clojure.org/about/rationale", "language": "en"},
  {"title": "Introduction · Crafting Interpreters", "url": "https://craftinginterpreters.com/introduction.html", "language": "en"},
  {"title": "Bug blindness", "url": "https://danluu.com/bug-blind/", "language": "en"},
  {"title": "The benchmarkpocalypse", "url": "https://danluu.com/benchpocalypse/", "language": "en"},
  {"title": "There's no point at which turning your brain off will work", "url": "https://danluu.com/brain-off/", "language": "en"},
  {"title": "There's no reason for software to be slow anymore", "url": "https://danluu.com/perf-opt/", "language": "en"},
  {"title": "Debian -- Our Philosophy: Why we do it and how we do it", "url": "https://www.debian.org/intro/philosophy", "language": "en"},
  {"title": "1. Whetting Your Appetite — Python 3.14.8 documentation", "url": "https://docs.python.org/3/tutorial/appetite.html", "language": "en"},
  {"title": "The circus freaks of open source", "url": "https://drewdevault.com/blog/Circus-freaks-of-FOSS/", "language": "en"},
  {"title": "Why is Hacker News like that?", "url": "https://drewdevault.com/blog/Why-is-HN-like-that/", "language": "en"},
  {"title": "Introduction :: Eloquent JavaScript", "url": "https://eloquentjavascript.net/00_intro.html", "language": "en"},
  {"title": "Don't you mean extinct?", "url": "https://fabiensanglard.net/extinct/index.html", "language": "en"},
  {"title": "My agent.md to improve LLM-assisted code quality", "url": "https://fabiensanglard.net/agent.md/index.html", "language": "en"},
  {"title": "Architecture, Performance, and Games · Introduction · Game Programming Patterns", "url": "https://gameprogrammingpatterns.com/architecture-performance-and-games.html", "language": "en"},
  {"title": "Introduction · Game Programming Patterns", "url": "https://gameprogrammingpatterns.com/introduction.html", "language": "en"},
  {"title": "Introduction: Why Lisp?", "url": "https://gigamonkeys.com/book/introduction-why-lisp.html", "language": "en"},
  {"title": "The GNU Manifesto - GNU Project - Free Software Foundation", "url": "https://www.gnu.org/gnu/manifesto.html", "language": "en"},
  {"title": "What is Free Software? - GNU Project - Free Software Foundation", "url": "https://www.gnu.org/philosophy/free-sw.html", "language": "en"},
  {"title": "Examples for the tcpdump and dig man pages", "url": "https://jvns.ca/blog/2026/03/10/examples-for-the-tcpdump-and-dig-man-pages/", "language": "en"},
  {"title": "Learning a few things about running SQLite", "url": "https://jvns.ca/blog/2026/07/17/learning-about-running-sqlite/", "language": "en"},
  {"title": "Links to CSS colour palettes", "url": "https://jvns.ca/blog/2026/05/04/css-colour-palettes/", "language": "en"},
  {"title": "Moving away from Tailwind, and learning to structure my CSS", "url": "https://jvns.ca/blog/2026/05/15/moving-away-from-tailwind--and-learning-to-structure-my-css-/", "language": "en"},
  {"title": "Some more things about Django I've been enjoying", "url": "https://jvns.ca/blog/2026/07/21/more-nice-django-things/", "language": "en"},
  {"title": "Testing Vue components in the browser", "url": "https://jvns.ca/blog/2026/05/02/testing-vue-components-in-the-browser/", "language": "en"},
  {"title": "감자 - 위키문헌, 우리 모두의 도서관", "url": "https://ko.wikisource.org/wiki/%EA%B0%90%EC%9E%90", "language": "ko"},
  {"title": "동백꽃 - 위키문헌, 우리 모두의 도서관", "url": "https://ko.wikisource.org/wiki/%EB%8F%99%EB%B0%B1%EA%BD%83", "language": "ko"},
  {"title": "메밀꽃 필 무렵 - 위키문헌, 우리 모두의 도서관", "url": "https://ko.wikisource.org/wiki/%EB%A9%94%EB%B0%80%EA%BD%83_%ED%95%84_%EB%AC%B4%EB%A0%B5", "language": "ko"},
  {"title": "벙어리 삼룡이 - 위키문헌, 우리 모두의 도서관", "url": "https://ko.wikisource.org/wiki/%EB%B2%99%EC%96%B4%EB%A6%AC_%EC%82%BC%EB%A3%A1%EC%9D%B4", "language": "ko"},
  {"title": "봄봄 - 위키문헌, 우리 모두의 도서관", "url": "https://ko.wikisource.org/wiki/%EB%B4%84%EB%B4%84", "language": "ko"},
  {"title": "술 권하는 사회 - 위키문헌, 우리 모두의 도서관", "url": "https://ko.wikisource.org/wiki/%EC%88%A0_%EA%B6%8C%ED%95%98%EB%8A%94_%EC%82%AC%ED%9A%8C", "language": "ko"},
  {"title": "운수 좋은 날 - 위키문헌, 우리 모두의 도서관", "url": "https://ko.wikisource.org/wiki/%EC%9A%B4%EC%88%98_%EC%A2%8B%EC%9D%80_%EB%82%A0", "language": "ko"},
  {"title": "week1", "url": "https://math.ucr.edu/home/baez/week1.html", "language": "en"},
  {"title": "Better Batteries", "url": "https://matklad.github.io/2026/08/20/better-batteries.html", "language": "en"},
  {"title": "Cancelation Terminology", "url": "https://matklad.github.io/2026/08/31/cancelation-terminology.html", "language": "en"},
  {"title": "Rust Glancer", "url": "https://matklad.github.io/2026/08/21/rust-glancer.html", "language": "en"},
  {"title": "Static Allocation, Constant Work", "url": "https://matklad.github.io/2026/09/02/static-allocation-constant-work.html", "language": "en"},
  {"title": "Zig's Io.Threaded is Neat", "url": "https://matklad.github.io/2026/08/06/neat-io-threaded.html", "language": "en"},
  {"title": "A custom virtual machine for the Stars! 4X game", "url": "https://nullprogram.com/blog/2026/09/17/", "language": "en"},
  {"title": "Concurrent, atomic MSI hash tables", "url": "https://nullprogram.com/blog/2026/05/06/", "language": "en"},
  {"title": "Examples of quick hash tables and dynamic arrays in C", "url": "https://nullprogram.com/blog/2025/01/19/", "language": "en"},
  {"title": "I have officially retired from Emacs", "url": "https://nullprogram.com/blog/2026/04/26/", "language": "en"},
  {"title": "My Journey with Touch Typing and Vim", "url": "https://nullprogram.com/blog/2017/04/01/", "language": "en"},
  {"title": "The quick and practical \"MSI\" hash table", "url": "https://nullprogram.com/blog/2022/08/08/", "language": "en"},
  {"title": "What's been going on in w64devkit the past year", "url": "https://nullprogram.com/blog/2026/09/20/", "language": "en"},
  {"title": "Server Driven UI 설계를 통한 UI 유연화", "url": "https://parksb.github.io/article/38.html", "language": "ko"},
  {"title": "소프트웨어 개발을 공학으로 만드는 것", "url": "https://parksb.github.io/article/44.html", "language": "ko"},
  {"title": "철도 시간표가 유닉스 시간이 되기까지", "url": "https://parksb.github.io/article/39.html", "language": "ko"},
  {"title": "함수형 프로그래밍의 설득력", "url": "https://parksb.github.io/article/40.html", "language": "ko"},
  {"title": "How Universities Should Prepare Founders", "url": "https://paulgraham.com/prepare.html", "language": "en"},
  {"title": "How to Convert Between Wealth and Income Tax", "url": "https://paulgraham.com/winc.html", "language": "en"},
  {"title": "How to Earn a Billion Dollars", "url": "https://paulgraham.com/earn.html", "language": "en"},
  {"title": "How to Lose Time and Money", "url": "https://paulgraham.com/selfindulgence.html", "language": "en"},
  {"title": "Making Startups Powerful", "url": "https://paulgraham.com/powerful.html", "language": "en"},
  {"title": "PostgreSQL: Documentation: 18: 2.2. Concepts", "url": "https://www.postgresql.org/docs/current/tutorial-concepts.html", "language": "en"},
  {"title": "Typography in ten minutes | Butterick’s Practical Typography", "url": "https://practicaltypography.com/typography-in-ten-minutes.html", "language": "en"},
  {"title": "What is Python? Executive Summary | Python.org", "url": "https://www.python.org/doc/essays/blurb/", "language": "en"},
  {"title": "'자바스크립트는 왜 그 모양일까?' 읽기", "url": "https://rinae.dev/posts/how-javascript-works-summary", "language": "ko"},
  {"title": "100권의 책을 스캔했다, 그리고 단 한 권도 읽지 않았다", "url": "https://rinae.dev/posts/scanned-100-books-read-none", "language": "ko"},
  {"title": "Claude Opus 5.5, GPT-6 Sol, GPT-6 Luna, and a new price war", "url": "https://simonwillison.net/2026/Sep/22/opus-and-sol-and-luna/", "language": "en"},
  {"title": "More books on this subject | Derek Sivers", "url": "https://sive.rs/u61", "language": "en"},
  {"title": "Appropriate Uses For SQLite", "url": "https://sqlite.org/whentouse.html", "language": "en"},
  {"title": "Most Widely Deployed SQL Database Engine", "url": "https://sqlite.org/mostdeployed.html", "language": "en"},
  {"title": "File Transfer with SSH, Tee and Base64 - Susam Pal", "url": "https://susam.net/file-transfer-with-ssh-tee-and-base64.html", "language": "en"},
  {"title": "Global Palindrome Day - Susam Pal", "url": "https://susam.net/global-palindrome-day.html", "language": "en"},
  {"title": "Import Readline - Susam Pal", "url": "https://susam.net/import-readline.html", "language": "en"},
  {"title": "Microcentury - Susam Pal", "url": "https://susam.net/microcentury.html", "language": "en"},
  {"title": "Peculiar Self-References - Susam Pal", "url": "https://susam.net/peculiar-self-references.html", "language": "en"},
  {"title": "ongoing by Tim Bray · Canceling Emily", "url": "https://www.tbray.org/ongoing/When/202x/2026/09/08/Emily-Got-Canceled", "language": "en"},
  {"title": "ongoing by Tim Bray · Clankers and Data Races", "url": "https://www.tbray.org/ongoing/When/202x/2026/09/01/Un-Racing", "language": "en"},
  {"title": "ongoing by Tim Bray · Five Views of the Wilcox Prairie", "url": "https://www.tbray.org/ongoing/When/202x/2026/08/17/Prairie-Views", "language": "en"},
  {"title": "ongoing by Tim Bray · Regulate and Standardize AI? Nope.", "url": "https://www.tbray.org/ongoing/When/202x/2026/09/18/On-Regulating-AI", "language": "en"},
  {"title": "ongoing by Tim Bray · Text Watermarking", "url": "https://www.tbray.org/ongoing/When/202x/2026/08/24/Text-Watermarking", "language": "en"},
  {"title": "ongoing by Tim Bray · The Purpose Isn’t What It Does", "url": "https://www.tbray.org/ongoing/When/202x/2026/09/24/The-Purpose-Isnt-What-It-Does", "language": "en"},
  {"title": "Hypertext Style: Cool URIs don't change.", "url": "https://www.w3.org/Provider/Style/URI", "language": "en"},
  {"title": "The original proposal of the WWW, HTMLized", "url": "https://www.w3.org/History/1989/proposal.html", "language": "en"},
];
