// SPDX-License-Identifier: GPL-3.0-only — © 2026 AIB Inc.
import type {Project} from './catalog.ts';
export const escapeHTML=(text:string)=>text.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export const attribution=(project:Project)=>`<p class="attribution">${project.attribution.label} <a href="${project.attribution.url}" target="_blank" rel="noopener noreferrer">${escapeHTML(project.attribution.name)} <span aria-hidden="true">↗</span></a></p>`;
export const tags=(items:string[])=>`<div class="tags">${items.map(t=>`<span>${escapeHTML(t)}</span>`).join('')}</div>`;
export const renderCredits=(projects:Project[])=>projects.map(p=>`<div><dt>${escapeHTML(p.title)}</dt><dd>${attribution(p)}</dd></div>`).join('');
export const renderIndex=(projects:Project[])=>projects.map(p=>`<a class="quick-work" href="${p.variants[0]!.path}" data-open="${p.id}" aria-label="Explore ${escapeHTML(p.title)}"><img src="${p.image}" alt="" width="52" height="42" loading="lazy"><span><small>${p.number} / ${p.category}</small>${escapeHTML(p.title)}</span></a>`).join('');
export const renderCards=(projects:Project[])=>projects.map(p=>`<article class="project-card reveal" id="project-${p.id}" style="--accent:${p.color}">
 <div class="artwork" data-project="${p.id}"><img src="${p.image}" alt="${escapeHTML(p.title+' — '+p.subtitle)}" loading="lazy" width="1536" height="1024"><div class="artwork-overlay"><div class="artwork-top"><span class="work-number">№ ${p.number}</span><span class="format">${p.id==='jelly'?'SOFT-BODY STUDY':p.id==='chroma'?'MOTION PLAYGROUND':'INTERACTIVE WORLD'}</span></div><div class="artwork-bottom"><span class="preview-hint">OPEN TO EXPLORE</span><span class="open-disc" aria-hidden="true">+</span></div></div><a class="artwork-open" href="${p.variants[0]!.path}" data-open="${p.id}" aria-label="Explore ${escapeHTML(p.title)}">${escapeHTML(p.title)}</a></div>
 <div class="project-meta"><p class="category">${p.category}</p><div class="project-title-row"><h3>${escapeHTML(p.title)}</h3><span>${p.year}</span></div><p class="subtitle">${escapeHTML(p.subtitle)}</p><p class="project-description">${escapeHTML(p.description)}</p>${attribution(p)}${tags(p.tech)}${p.variants.length>1?`<div class="variant-picker" aria-label="Fruit Jelly variation">${p.variants.map((v,i)=>`<button data-variant="${v.id}" aria-pressed="${i===0}">${v.name}</button>`).join('')}</div>`:''}<a class="project-details" href="${p.variants[0]!.path}" data-open="${p.id}">Explore the experiment <span aria-hidden="true">→</span></a></div></article>`).join('');
