// SPDX-License-Identifier: GPL-3.0-only — © 2026 AIB Inc.
import type {Project} from './catalog.ts';
import {icon} from './icons.ts';
export const escapeHTML=(text:string)=>text.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export const attribution=(project:Project,showIcon=true)=>project.attribution?`<p class="attribution">${project.attribution.label} <a href="${project.attribution.url}" target="_blank" rel="noopener noreferrer">${escapeHTML(project.attribution.name)}${showIcon?` ${icon('link-simple')}`:''}</a></p>`:'<p class="attribution">Inspired by a supplied recording · Creator unknown</p>';
export const tags=(items:string[])=>`<div class="tags" aria-label="Technologies">${items.map(t=>`<span>${escapeHTML(t)}</span>`).join('')}</div>`;
export const renderCredits=(projects:Project[])=>projects.map(p=>`<div><dt>${escapeHTML(p.title)}</dt><dd>${attribution(p)}</dd></div>`).join('');
export const renderIndex=(projects:Project[])=>projects.map(p=>`<a class="quick-work" href="${p.variants[0]!.path}" data-work="${p.id}" target="_blank" rel="noopener noreferrer" aria-label="Open ${escapeHTML(p.title)}"><img src="${p.image}" alt="" width="52" height="42" loading="lazy"><span><small>${p.number} / ${p.category}</small>${escapeHTML(p.title)}</span></a>`).join('');
export const renderCards=(projects:Project[])=>projects.map(p=>`<article class="project-card reveal" id="project-${p.id}" style="--accent:${p.color}">
 <div class="artwork" data-project="${p.id}"><img src="${p.image}" alt="${escapeHTML(p.title+' — '+p.subtitle)}" loading="lazy" width="1536" height="1024"><div class="artwork-overlay"><div class="artwork-top"><span class="work-number">№ ${p.number}</span><span class="format">${p.id==='jelly'?'SOFT-BODY STUDY':p.id==='chroma'?'MOTION PLAYGROUND':'INTERACTIVE WORLD'}</span></div><div class="artwork-bottom"><span class="preview-hint">${icon('play')}<span class="preview-label">Open experience</span></span></div></div><a class="artwork-open" href="${p.variants[0]!.path}" data-work="${p.id}" target="_blank" rel="noopener noreferrer" aria-label="Open ${escapeHTML(p.title)}">${escapeHTML(p.title)}</a></div>
 <div class="project-heading"><p class="category">${p.category}</p><div class="project-title-row"><h3>${escapeHTML(p.title)}</h3><span>${p.year}</span></div><p class="subtitle">${escapeHTML(p.subtitle)}</p></div>
 <div class="project-meta"><p class="project-description">${escapeHTML(p.description)}</p>${attribution(p,false)}${tags(p.tech)}${p.variants.length>1?`<div class="variant-picker" aria-label="${escapeHTML(p.title)} variations">${p.variants.map((v,i)=>`<button data-variant="${v.id}" aria-pressed="${i===0}">${escapeHTML(v.name)}</button>`).join('')}</div>`:''}<dl class="project-specs">${p.specs.map(([name,value])=>`<div><dt>${escapeHTML(name)}</dt><dd>${escapeHTML(value)}</dd></div>`).join('')}</dl><div class="project-actions"><a class="solid-button" href="${p.variants[0]!.path}" data-work="${p.id}" target="_blank" rel="noopener noreferrer" aria-label="Open ${escapeHTML(p.title)}">Open experience ${icon('arrow-right')}</a><a class="outline-button" href="${p.source}" download aria-label="Download ${escapeHTML(p.title)} source">${icon('download-simple')} Download source</a></div><p class="license">${escapeHTML(p.license)}</p></div></article>`).join('');
